### ISSUE TITLE
Question about empty_bg

### ISSUE THREAD

**Issue by 159421** [ozantezcan/BSUV-Net-inference#6]
Thanks a lot for your great work.  I want to ask about what requirement need for the image when using empty_bg="manual" to manually specify the background model?

**Comment by ozantezcan** [comment]
I just pushed an example for empty_bg="manual". Please see configs/infer_config_manualBG.py. Let me know if you need any further help.

**Comment by 159421** [comment]
Thanks for your great work! Can I use a trained model that uses the RGB+FPM channels (12-channel input) to do that?

**Comment by 159421** [comment]
Thank you! If I want to use the trained model which uses the RGB+FPM channels(12-channel input) and using manual background, do I need to download HRNet_v2 model files and place them in utils/segmentation/hrnet_v2 folder? But I cannot find the folder.

**Comment by ozantezcan** [comment]
Yes, you need to create a folder named hrnet_v2 in utils/segmentation and put the model files (encoder_epoch_30.pth and decoder_epoch_30.pth) in it.

**Comment by 159421** [comment]
After I create the folder and put the model files in it. When I try to run the example video, I got a runtime error below:
RuntimeError: Given groups=1, weight of size 64 12 3 3, expected input[1, 9, 288, 352] to have 12 channels, but got 9 channels instead

**Comment by ozantezcan** [comment]
You need to change infer_config for using a 12-channels model. You can do it by uncommenting lines 20-24 of infer_config_manualBG.py and commenting lines 27-29.
